# Generated by Django 3.0.6 on 2020-05-05 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('nombre_corto', models.CharField(max_length=20, verbose_name='Nombre Corto')),
                ('esta_activo', models.BooleanField(default=True, verbose_name='Esta Activo')),
            ],
        ),
    ]
