# Generated by Django 3.0.6 on 2020-05-05 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0003_auto_20200505_1843'),
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habilidades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilidad', models.CharField(max_length=50, verbose_name='Habilidad')),
            ],
            options={
                'verbose_name': 'Habilidad',
                'verbose_name_plural': 'Habilidades Empleado',
            },
        ),
        migrations.AlterModelOptions(
            name='empleado',
            options={'ordering': ['primer_nombre', 'apellidos'], 'verbose_name': 'Empleado', 'verbose_name_plural': 'Mis Empleados'},
        ),
        migrations.AlterUniqueTogether(
            name='empleado',
            unique_together={('primer_nombre', 'departamento')},
        ),
    ]
