# Generated by Django 3.0.6 on 2020-05-06 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0004_empleado_hoja_vida'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='nombre_completo',
            field=models.CharField(blank=True, max_length=120, verbose_name='Nombre Completo'),
        ),
    ]
